### PR TITLE
Test update after changes in a IntegrationsBundle PR 48

### PR DESCRIPTION
**Pull request by escopecz**
https://github.com/mautic-inc/plugin-integrations/pull/48

### CODE REVIEW

**Comment by escopecz** [comment]
I've created https://backlog.acquia.com/browse/MAUT-2779 to fix the Ci tests

**Review by ondrejsibl — APPROVED** [review]
Tests are now working on beta

**Comment by escopecz** [comment]
This is ready to merge but I'd rather merge it after https://github.com/mautic-inc/plugin-integrations/pull/48 is merged to avoid Jenkins issues.

**Comment by escopecz** [comment]
Argh, Pull Reminders are going to bug me every day when this will be open. I'm going to risk it and merge. Hopefully it won't cause any issues.

**Pull request merged**
